### ISSUE TITLE
Notifications can't parse specials chars like plus or dots

### ISSUE THREAD

**Issue by locopol** [HeyHeyChicken/My-LaMetric-Time-Android#1]
Hi Man, your app works amazing, i love it, but i found this issue related with the some characters handle, this is the explain:

- this is the notification sended without specials chars (like dot), for example:

![imagen](https://user-images.githubusercontent.com/50225514/217093576-2069916a-df30-4cf6-b2de-8f6a5aee7fd3.png)

- the server receive the notification and display the message correctly:

![imagen](https://user-images.githubusercontent.com/50225514/217093746-09156ce1-1ba9-444c-a551-2df9742baddf.png)

- but if put a dot in the message of notification, the server processed the notification but the server doesn't show the message:

![imagen](https://user-images.githubusercontent.com/50225514/217094073-8b6a2428-8e18-4e99-af87-c84ef65909a4.png)

- and the server only shows the icon, without animation....

![imagen](https://user-images.githubusercontent.com/50225514/217094696-558613d8-6d8b-45d8-8018-9916ef7dbe25.png)

best regards

**Comment by HeyHeyChicken** [comment]
[Answered here](//github.com/HeyHeyChicken/No-Clock/issues/1)
